server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型  默认的数据源是org.apache.tomcat.jdbc.pool.DataSource
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wxy.springcloud.entities

eureka:
  client:
    register-with-eureka: true  # 注册近eurekaServer
    fetch-registry: true        # 抓取已有注册信息，单节点无所谓，集群要设置true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka/

